version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: nest_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testFproject
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env

app:
  build: .
  ports:
    - '3000:3000'
  depends_on:
    - postgres  
  environment:
    DATABASE_NAME: testFproject
    DATABASE_USER: admin
    DATABASE_PASSWORD: root
    DATABASE_PORT: 5432